/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elliot_clicker_jni_JNIAdapter */

#ifndef _Included_com_elliot_clicker_jni_JNIAdapter
#define _Included_com_elliot_clicker_jni_JNIAdapter
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_elliot_clicker_jni_JNIAdapter
	* Method:    sendKeysToWindow
	* Signature: (Ljava/lang/String;)V
	*/
	JNIEXPORT void JNICALL Java_com_elliot_clicker_jni_JNIAdapter_sendKeysToWindow
	(JNIEnv *, jobject, jstring);

	/*
	* Class:     com_elliot_clicker_jni_JNIAdapter
	* Method:    getGameValues
	* Signature: ()Lcom/elliot/clicker/entity/GameValues;
	*/
	JNIEXPORT jobject JNICALL Java_com_elliot_clicker_jni_JNIAdapter_getGameValues
	(JNIEnv *, jobject);

	/*
	* Class:     com_elliot_clicker_jni_JNIAdapter
	* Method:    sendClicksToWindowByPositionAndAmountAndDelay
	* Signature: (IIIJ)V
	*/
	JNIEXPORT void JNICALL Java_com_elliot_clicker_jni_JNIAdapter_sendClicksToWindowByButtonAndPositionAndAmountAndDelay
	(JNIEnv *, jobject, jint, jint, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
